/**
 * 路由导航
 * Created by zhouL on 2025/10/11.
 */
export class RouterGuide {
  /** 启动页 */
  public static readonly SplashPage = 'SplashPage'
  /** 主页 */
  public static readonly MainPage = 'MainPage'
  /** ComponentV2装饰器用例 */
  public static readonly ComponentV2Page = 'ComponentV2Page'
  /** Local注解Demo类 */
  public static readonly LocalDemoPage = 'LocalDemoPage'
  /** ObservedV2注解Demo类 */
  public static readonly ObservedV2DemoPage = 'ObservedV2DemoPage'
  /** Param搭配Require注解Demo类 */
  public static readonly ParamRequireDemoPage = 'ParamRequireDemoPage'
  /** Param搭配Once注解Demo类 */
  public static readonly ParamOnceDemoPage = 'ParamOnceDemoPage'
  /** Param搭配Event注解Demo类 */
  public static readonly ParamEventDemoPage = 'ParamEventDemoPage'
  /** 双向绑定demo类 */
  public static readonly DoubleBindDemoPage = 'DoubleBindDemoPage'
  /** Provider注解Demo类 */
  public static readonly ProviderDemoPage = 'ProviderDemoPage'
  /** Computed注解Demo类 */
  public static readonly ComputedDemoPage = 'ComputedDemoPage'
  /** Monitor注解Demo类 */
  public static readonly MonitorDemoPage = 'MonitorDemoPage'
  /** 可观察对象转换Demo类 */
  public static readonly MakeObservedDemoPage = 'MakeObservedDemoPage'
  /** Json转换测试 */
  public static readonly JsonPage = 'JsonPage'
  /** Preferences测试类 */
  public static readonly PreferencesPage = 'PreferencesPage'
  /** Promise测试类 */
  public static readonly PromisePage = 'PromisePage'
  /** 刷新/加载更多测试类 */
  public static readonly RefreshLoadPage = 'RefreshLoadPage'
  /** EventBus测试类 */
  public static readonly EventBusPage = 'EventBusPage'
  /** EventBus测试详情类 */
  public static readonly EventBusDetailPage = 'EventBusDetailPage'
  /** 基类容器测试类 */
  public static readonly ContainerPage = 'ContainerPage'
  /** 基础状态控件容器Demo类 */
  public static readonly BaseContainerPage = 'BaseContainerPage'
  /** 基础状态和下拉刷新容器Demo类 */
  public static readonly RefreshContainerPage = 'RefreshContainerPage'
  /** 基础状态控件、中部刷新控件和顶部/底部扩展容器Demo类 */
  public static readonly SandwichContainerPage = 'SandwichContainerPage'
}