/**
 * 路由导航
 * Created by zhouL on 2025/10/11.
 */
export class RouterGuide {
  /** 启动页 */
  public static readonly SplashPage = 'SplashPage'
  /** 主页 */
  public static readonly MainPage = 'MainPage'
  /** ComponentV2装饰器用例 */
  public static readonly ComponentV2Page = 'ComponentV2Page'
  /** Json转换测试 */
  public static readonly JsonPage = 'JsonPage'
  /** mvvm用例页面 */
  public static readonly MvvmPage = 'MvvmPage'
  /** Preferences测试类 */
  public static readonly PreferencesPage = 'PreferencesPage'
  /** Promise测试类 */
  public static readonly PromisePage = 'PromisePage'
  /** 刷新/加载更多测试类 */
  public static readonly RefreshLoadPage = 'RefreshLoadPage'

}